# version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql_aparcamiento
    environment:
      MYSQL_ROOT_PASSWORD: blas1234
      MYSQL_DATABASE: db_aparcamiento
    networks:
      - red_aparcamiento
    volumes:
      - volume_aparcamiento_bdd:/var/lib/mysql
  
  python:
    build: .
    restart: always
    container_name: python_aparcamiento
    depends_on:
      - mysql
    networks:
      - red_aparcamiento
    ports:
      - "80:5000"
    volumes:
      - .:/app
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - red_aparcamiento
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: blas1234



networks:
  red_aparcamiento:
    driver: bridge
volumes:
  volume_aparcamiento_bdd: